version: "3.9"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: filter-bot
    restart: always
    volumes:
      - ./logs/:/bot/logs
    env_file:
      - ./.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.verifier.rule=Host(`auth.${APP_SERVICE_HOSTNAME}`)"
      - "traefik.http.routers.verifier.tls=true"
      - "traefik.http.routers.verifier.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.verifier.entrypoints=https"
      - "traefik.http.routers.verifier.service=verifier"
      - "traefik.http.services.verifier.loadbalancer.server.port=5050"
    ports:
      - 5050:5050
